server:
  port: 8090

spring:
  datasource:
    url: "jdbc:mysql://47.103.146.40:3306/trade?characterEncoding=utf-8"
    username: "root"
    password: "Root@2019"
    driver-class-name: "com.mysql.jdbc.Driver"
    type: "com.alibaba.druid.pool.DruidDataSource"

mybatis:
  mapper-locations: "classpath:mapper/*.xml"