server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
      location: "F:\\tmp_images\\"
      resolve-lazily: false
  datasource:
    url: "jdbc:mysql://47.103.146.40:3306/trade?characterEncoding=utf-8"
    username: "root"
    password: "Root@2019"
    driver-class-name: "com.mysql.jdbc.Driver"
    type: "com.alibaba.druid.pool.DruidDataSource"
  redis:
    host: "101.133.161.59"
    port: 6379
    database: 1
    password: "safaf234vvFAWd234wer432"
    jedis:
      pool:
        max-active: 50
        min-idle: 20
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file-load-setting:
  local-image-dictionary: "F:\\images\\"
  ftp-host: "47.103.146.40"
  ftp-port: 21
  ftp-user: "virftp"
  ftp-password: "helloworld"
  ftp-work-path: "/image/"
  ftp-timeout: 1000
  nginx-resource-url: "http://47.103.146.40:8888"

logging:
  level:
    org.study.dao: debug

mq:
  name-server:
    addr: "47.103.146.40:9876"
  topic-name: "stock"
  decr-stock-group-name: "decr_stock_group"
  incr-stock-group-name: "incr_stock_group"
  decr-sales-group-name: "decr_sales_group"
  incr-sales-group-name: "incr_sales_group"
  decr-stock-incr-sales-group-name: "decr_stock_incr_sales_group"
  send-timeout: 10000

alipay:
  return-url: "http://localhost:8090/api/order/trade_pay"